/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT-0
 */
import * as path from 'node:path'
import { Stack, StackProps } from 'aws-cdk-lib'
import * as s3deploy from 'aws-cdk-lib/aws-s3-deployment'
import { Construct } from 'constructs'
import { RootConfig } from '../config'
import { setNamespace } from '../utils/namespace'
import { ApiWeb } from '../constructs/ApiWeb'
import { PersistentBackendStack } from './PersistentBackendStack'

export interface BackendStackProps extends StackProps, Omit<RootConfig, 'env'> {
  readonly persistent: PersistentBackendStack
}

export class BackendStack extends Stack {
  constructor(scope: Construct, id: string, props: BackendStackProps) {
    super(scope, id, props)

    setNamespace(this, props.namespace)

    const { persistent } = props

    // ApiWeb construct
    const apiWeb = new ApiWeb(this, 'ApiWeb', {
      region: this.region,
      account: this.account,
      userPool: persistent.userPool,
      customerLocations: persistent.customerLocations,
      warehouses: persistent.warehouses,
      solverJobs: persistent.solverJobs,
      deliveryJobs: persistent.deliveryJobs,
      orders: persistent.orders,
      vehicles: persistent.vehicles,
      distCache: persistent.distanceCache,
      distanceCacheBucket: persistent.distanceCacheBucket,
      parameterStoreKeys: props.parameterStoreKeys,
    })

    // Website bundle deployment (React app)
    // Exclude appvars.js from the bundle — it is generated separately by AppVariablesDeployment
    const websiteBundlePath = path.resolve(process.cwd(), props.assets.websiteBundlePath)
    new s3deploy.BucketDeployment(this, 'WebsiteDeployment', {
      sources: [s3deploy.Source.asset(websiteBundlePath)],
      destinationBucket: persistent.websiteBucket,
      exclude: ['static/appvars.js'],
    })

    // AppVariables: generate JS file with runtime config
    // Frontend expects global `appVariables` with keys: REGION, USERPOOL_ID, USERPOOL_CLIENT_ID, API_URL
    const appVarsContent = [
      '// Auto-generated by CDK - do not edit',
      `var appVariables = {`,
      `  REGION: "${this.region}",`,
      `  USERPOOL_ID: "${persistent.userPool.userPoolId}",`,
      `  USERPOOL_CLIENT_ID: "${persistent.userPoolClient.userPoolClientId}",`,
      `  API_URL: "${apiWeb.restApi.url}"`,
      `};`,
    ].join('\n')

    new s3deploy.BucketDeployment(this, 'AppVariablesDeployment', {
      sources: [s3deploy.Source.data('static/appvars.js', appVarsContent)],
      destinationBucket: persistent.websiteBucket,
      prune: false,
    })
  }
}
