# Dev profile: activated with --spring.profiles.active=dev

# Routing (local map file assumed to be pre-downloaded)
app.routing.local-osm-dir=~/.graphhopper/openstreetmap
app.routing.local-graphhopper-dir=~/.graphhopper/graphhopper
app.routing.osm-file=south-korea-latest.osm.pbf

# Dispatch config
app.dispatch.config.warehouse-code=95001200
app.dispatch.config.order-date=20230101
app.dispatch.config.max-contracted-vehicles=10
app.dispatch.config.max-time-groups=3

# Distance cache persistence
app.routing.cache.persistence-type=s3
app.routing.cache.s3-bucket-name=/DevProto/S3/DistanceCache/BucketName
app.routing.cache.ddb-table-name=/DevProto/DDB/DistanceCache/TableName
app.routing.cache.file-path=cache/output.latlongcache

# AWS
aws.profile=route-opt
aws.region=ap-northeast-2

# Dev Server
server.port=8888

# OptaPlanner
optaplanner.solver.solver-config-xml=solver-config.xml

# Logging
logging.level.org.optaplanner=DEBUG
logging.level.dev.aws.proto=DEBUG
