# Test profile: activated with --spring.profiles.active=test

# AWS
aws.profile=route-opt
aws.region=ap-northeast-2

# Routing
app.routing.local-osm-dir=~/.graphhopper/openstreetmap
app.routing.local-graphhopper-dir=~/.graphhopper/graphhopper

# Server
server.port=8888

# OptaPlanner
optaplanner.solver.solver-config-xml=solver-config.xml

# Logging
logging.level.org.optaplanner=DEBUG
logging.level.dev.aws.proto=DEBUG
